import mongoose from 'mongoose';

const personalTaskSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true,
  },
  title: {
    type: String,
    required: true,
    trim: true,
    maxlength: 160,
  },
  description: {
    type: String,
    trim: true,
    maxlength: 1500,
    default: '',
  },
  status: {
    type: String,
    enum: ['todo', 'in_progress', 'completed'],
    default: 'todo',
    index: true,
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high'],
    default: 'medium',
  },
  dueDate: {
    type: Date,
    default: null,
  },
  completedAt: {
    type: Date,
    default: null,
  },
  autoGenerateLinkedInPost: {
    type: Boolean,
    default: true,
  },
  lastAutoGeneratedPost: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'SocialPostV2',
    default: null,
  },
  autoPostStatus: {
    type: String,
    enum: ['none', 'pending_approval', 'published', 'failed', 'already_generated'],
    default: 'none',
  },
  autoPostMessage: {
    type: String,
    default: null,
  },
}, { timestamps: true });

personalTaskSchema.index({ user: 1, createdAt: -1 });

export default mongoose.model('PersonalTaskV2', personalTaskSchema);

